import ExcelJS from "exceljs";
import type { RegistrationDocument } from "@/models/Registration";
import type { QuestionnaireResponseDocument } from "@/models/QuestionnaireResponse";
import type { FeedbackFormDocument } from "@/models/FeedbackForm";
import type { FeedbackResponseDocument } from "@/models/FeedbackResponse";
import type { WorkshopDocument } from "@/models/Workshop";
export interface ExportLookups { registrations: Map<string, RegistrationDocument>; workshops: Map<string, WorkshopDocument>; }
const genders: Record<string, string> = { male: "Male", female: "Female", other: "Other", prefer_not_to_say: "Prefer not to say" };
const userColumns = () => [{ header: "Registration Number", key: "registrationNumber", width: 20 }, { header: "Name", key: "name", width: 24 }, { header: "Age", key: "age", width: 8 }, { header: "Gender", key: "gender", width: 18 }, { header: "WhatsApp Number", key: "phone", width: 18 }, { header: "Email", key: "email", width: 28 }, { header: "City", key: "city", width: 18 }, { header: "Preferred Language", key: "preferredLanguage", width: 18 }, { header: "Workshop", key: "workshop", width: 28 }, { header: "Workshop Date", key: "workshopDate", width: 18 }];
function id(value: unknown): string { return value == null ? "" : String(value); }
function date(value: unknown): string { const parsed = new Date(value as string); return Number.isNaN(parsed.getTime()) ? "" : parsed.toLocaleString("en-IN"); }
function row(r: RegistrationDocument | undefined, workshops: Map<string, WorkshopDocument>): Record<string, string | number> { const w = r?.workshopId ? workshops.get(id(r.workshopId)) : undefined; return { registrationNumber: r?.registrationNumber ?? "", name: r?.name ?? "", age: r?.age ?? "", gender: r ? (genders[r.gender] ?? r.gender) : "", phone: r?.phone ?? "", email: r?.email ?? "", city: r?.city ?? "", preferredLanguage: r?.preferredLanguage ?? "", workshop: w?.title ?? "", workshopDate: w ? date(w.date) : "" }; }
function sheet(name: string) { const workbook = new ExcelJS.Workbook(); return { workbook, sheet: workbook.addWorksheet(name) }; }
export async function buildRegistrationsWorkbook(registrations: RegistrationDocument[], workshops: Map<string, WorkshopDocument>): Promise<Buffer> { const x = sheet("Registrations"); x.sheet.columns = [...userColumns(), { header: "Registration Status", key: "status", width: 20 }, { header: "Payment Status", key: "paymentStatus", width: 18 }, { header: "Registration Date", key: "createdAt", width: 20 }, { header: "Joined WhatsApp Community", key: "joinedCommunity", width: 24 }]; x.sheet.getRow(1).font = { bold: true }; registrations.forEach((r) => x.sheet.addRow({ ...row(r, workshops), status: r.status ?? "", paymentStatus: r.paymentStatus ?? "", createdAt: date(r.createdAt), joinedCommunity: r.joinedCommunity ? "Yes" : "No" })); return Buffer.from(await x.workbook.xlsx.writeBuffer()); }
export function buildExportFilename(title: string, date: Date): string { const d = new Date(date); return `${title}-${String(d.getUTCDate()).padStart(2, "0")}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${d.getUTCFullYear()}.xlsx`; }
export function buildTimestampedExportFilename(name: string): string { const d = new Date(); return `${name}-${String(d.getUTCDate()).padStart(2, "0")}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${d.getUTCFullYear()}.xlsx`; }
export async function buildQuestionnaireResponsesWorkbook(responses: QuestionnaireResponseDocument[], lookups: ExportLookups): Promise<Buffer> { const x = sheet("Questionnaire Responses"); const questions = [...new Set(responses.flatMap((r) => Array.isArray(r.questions) ? r.questions.map((q) => q.questionText) : [r.question1Text, r.question2Text, r.question3Text]).filter((q): q is string => Boolean(q)))]; x.sheet.columns = [...userColumns(), ...questions.map((q, i) => ({ header: q, key: `q${i}`, width: 40 })), { header: "Submission Date", key: "createdAt", width: 20 }]; x.sheet.getRow(1).font = { bold: true }; responses.forEach((r) => { const data: Record<string, string | number> = { ...row(lookups.registrations.get(id(r.registrationId)), lookups.workshops), createdAt: date(r.createdAt) }; const answers = Array.isArray(r.questions) ? r.questions.map((q) => [q.questionText, q.answer] as const) : [[r.question1Text, r.question1Answer], [r.question2Text, r.question2Answer], [r.question3Text, r.question3Answer]]; answers.forEach(([q, a]) => { const i = q ? questions.indexOf(q) : -1; if (i >= 0) data[`q${i}`] = a ?? ""; }); x.sheet.addRow(data); }); return Buffer.from(await x.workbook.xlsx.writeBuffer()); }
export async function buildFeedbackResponsesWorkbook(form: FeedbackFormDocument, responses: FeedbackResponseDocument[], lookups: ExportLookups): Promise<Buffer> { const x = sheet("Feedback Responses"); const labels = [...new Set(responses.flatMap((r) => (r.answers ?? []).map((a) => a.label ?? form.fields.find((f) => f.key === a.fieldKey)?.label ?? a.fieldKey)))]; x.sheet.columns = [...userColumns(), { header: "Feedback Form", key: "form", width: 28 }, ...labels.map((l, i) => ({ header: l, key: `f${i}`, width: 35 })), { header: "Submission Date", key: "createdAt", width: 20 }]; x.sheet.getRow(1).font = { bold: true }; responses.forEach((r) => { const data: Record<string, string | number> = { ...row(r.registrationId ? lookups.registrations.get(id(r.registrationId)) : undefined, lookups.workshops), form: form.title ?? "", createdAt: date(r.createdAt) }; (r.answers ?? []).forEach((a) => { const l = a.label ?? form.fields.find((f) => f.key === a.fieldKey)?.label ?? a.fieldKey; const value = Array.isArray(a.value) ? a.value.join(", ") : typeof a.value === "boolean" ? (a.value ? "Yes" : "No") : a.value == null ? "" : String(a.value); data[`f${labels.indexOf(l)}`] = value; }); x.sheet.addRow(data); }); return Buffer.from(await x.workbook.xlsx.writeBuffer()); }
